export const VALIDATION_REGEX = {
  name: /^[A-Za-z]+(?: [A-Za-z]+)*$/,
  companyName: /^[A-Za-z0-9]+(?:[ .&'-][A-Za-z0-9]+)*$/,
  email:/^(?!\.)[A-Za-z0-9._%+-]+(?<!\.)@[A-Za-z0-9-]+(\.[A-Za-z]{2,})+$/,
  city:/^[A-Za-z]+(?: [A-Za-z]+)*$/,
  price: /^[\d,]+(\.\d+)?$/,
  stock: /^[\d,]+$/,
  phone: /^\d+$/,
  productName: /^[A-Za-z0-9][A-Za-z0-9\s\-'",.&()/]*[A-Za-z0-9)]$/,
  brandName:/^[A-Za-z0-9]+(?:[ '&-][A-Za-z0-9]+)*$/,
  upi:/^[A-Za-z0-9._-]+@[A-Za-z0-9]+$/,
  accountHolderName:/^[A-Za-z]+(?:[ .'][A-Za-z]+)*$/,
  accountNumber:/^\d{9,18}$/,
  ifscCode:/^[A-Za-z]{4}0[A-Za-z0-9]{6}$/,
  bankName:/^[A-Za-z]+(?:[ .&][A-Za-z]+)*$/,
  pincode: /^\d{6}$/,
};
